### ISSUE TITLE
Result ordering for multiple selectors

### ISSUE THREAD

**Issue by jpe90** [Shinmera/CLSS#14]
Hello! 

In jquery and other HTML traversal libraries, results from applying multiple comma delimited selectors (e.g. "div, span, p") are returned in DOM order, while clss groups by selector. e.g. for HTML

```
<p>One</p>
<h1>Two</h1>
<p>Three</p>

```
Applying `$("p,h1")` will return nodes in order "One", "Two", "Three", while `clss:select "p,h1" ...` will return nodes One and Three followed by Two.

Do you know if it's possible to get DOM ordering from CLSS (or lquery/plump)? I'm using lquery and attempting to replicate some web scraping I did in other projects.

Thank you for all your libraries!!

**Comment by Shinmera** [comment]
This would require changing the way clss does searches, so it's not possible without patching the library. I'd accept such a patch as long as it wouldn't sacrifice search speed, but don't have the time to implement it myself I'm afraid.

**Comment by jpe90** [comment]
Understood, thank you

**Comment by aartaka** [comment]
I may be necro-bumping, but this hack might be useful to someone, like me, who wants ordered results too. Here's a rough draft of an order-preserving CLSS-like select:
``` lisp
(defmethod ordered-select (selector (root plump:nesting-node))
  "A re-implementation of `clss:select' with the goal of preserving elements order.

SELECTOR is any selector acceptable to `clss', including the compiled one and
string one."
  (let ((matched-nodes '()))
    (labels ((collect-if-match (element)
               (when (clss:node-matches-p selector element)
                 (push element matched-nodes))
               (map nil #'collect-if-match (plump:child-elements element))))
      (collect-if-match root)
      (coerce (nreverse matched-nodes) 'vector))))
```
The performance is bearable, here's an example for Hacker News toplevel page:
```
> (defvar hn-dom (plump:parse (dex:get "https://news.ycombinator.com")))
HN-DOM
> (time (clss:select "a" hn-dom))
Evaluation took:
  0.004 seconds of real time
  0.000636 seconds of total run time (0.000636 user, 0.000000 system)
  25.00% CPU
  1,571,869 processor cycles
  32,752 bytes consed
<...>
;; Don't mind the package prefix, this function is for now part of Nyxt code.
> (time (nyxt/dom:ordered-select "a" hn-dom))
Evaluation took:
  0.004 seconds of real time
  0.002298 seconds of total run time (0.002298 user, 0.000000 system)
  50.00% CPU
  5,553,824 processor cycles
  751,232 bytes consed
<...>
```

@Shinmera, I can try squeezing some performance out of it and open a PR with this function as the _additional_ API point (I don't feel like replacing the whole `clss:select` infrastructure, it looks quite thought-out). Is that an acceptable course of action?

**Comment by Shinmera** [comment]
Sure, that sounds fine!
