### ISSUE TITLE
How to access the text of a node ?

### ISSUE THREAD

**Issue by vindarel** [Shinmera/CLSS#4]
Hi, I'm experimenting with plump and clss (and Common Lisp, newbie here). How can we access the text of a node ?

I do:

    (setq req (dex:get "http://localhost:5000/"))
    (setq soup (plump:parse req))
    (clss:select "#main" soup)
    
this gives me back a plump-dom element. But how can I see and save its value ? In Python and beautifulsoup for example, we can simply call the `text` attribute. 

Maybe should I use lquery ? I'd have another question then :]

**Comment by Shinmera** [comment]
Use the plump-dom functions as listed [in the documentation](http://shinmera.github.io/plump/#PLUMP-DOM)

**Comment by vindarel** [comment]
Thanks, it wasn't obvious to me to refer to plump's doc, even if it's indicated. It was easy now.
