### ISSUE TITLE
Depth First Search

### ISSUE THREAD

**Issue by libre-man** [Shinmera/CLSS#6]
It would be nice to be able to select multiple items with a single function call. I know lquery lets me do this, but there could be some nice optimization possibilities if we could also do this in clss.

Lets assume we need to do a query such like this one: `(select "very-specific" (select "table" (select ".columns" *doc*)))`. And lets say that the ".columns" selector results in 100 matches, the "table" selector results in 100 matches per match and the "very-specific" selector in only one match per match of the ".columns" selector. This means the resulting vector is 100 long, however we had an intermediate vector of 10000 long.

I think this could be doable by passing an accumulator to `match-pair`. Would you be interested in a PR that would add this functionality?

**Comment by Shinmera** [comment]
I'm not quite sure I understand. Your first paragraph sounds like you just want to do `"a,b"` which is possible in CLSS. Your second paragraph sounds like you just want `".columns table very-specific"`, which of course is also possible.

Do you want to select parents plus specific children into a vector? Do you want to select into two separate vectors somehow?

**Comment by libre-man** [comment]
Sorry I wasn't really clear, it was quite late.

The thing I want to do is "table td .very-specific", however this seems to a simple loop that is equivalent to `(select "very-specific (select  "td" ....)`. The problem with this is if I have a HTML document like this:
```html
<body>
  <table>
    <tbody>
      <!-- With multiple tr's -->
      <tr>
        <td>
          <div class="very-specific">
            Should match
          </div>
        </td>
        <!-- This multiple times -->
        <td>
          <div class="other-class"> </div>
        </td>
        <div class="very-specific">
          Should not match
        </div>
      </tr>
    </tbody>
  </table>
</body>
```

Then the current looping pattern creates a vector with each `td` in it before filtering them out. However it could simply not store these non matching items the first time. Or in other words, the current approach seems to be a breadth first search, however it might be a worthwhile idea to give the user the opportunity to do a depth first search.

**Comment by Shinmera** [comment]
I see, that's a very reasonable proposition. I don't remember my rationale for accumulating the results in each combinator step, it's been too long. 

Unfortunately I currently don't have the time to look into this, so someone else would have to come along and do it, or you might have to wait for a rather long time for it to happen.

**Comment by libre-man** [comment]
I wouldn't mind doing it, it doesn't seem to be too difficult. I'll try to submit a pull request somewhere this week. Would you prefer to keep the possibility of breadth first search as well?

**Comment by Shinmera** [comment]
Right now I can't imagine breadth-first being faster than depth-first for any possible scenario, so I don't see the point in keeping it around if they both produce correct results for all combinators. I wouldn't mind seeing some benchmarks as well, of course.

**Comment by libre-man** [comment]
Sorry this took longer than expected because of my schedule. Anyway I implemented DFS and the results are somewhat positive.

First of all the change did not have a large influence, not on speed and not on consing behavior. However after looking at the profiles the reason of this was that another function was consing like crazy. The problem was doing `member` on a `split`, `split` conses to new strings and this is not necessary, combining `member` and `split` solves this problem.

This change led to two times increase in performance for my test case. DFS now did have an advantage over BFS with around half of the bytes consed and a ~8% performance increase for the worst case scenario for BFS.

**Comment by Shinmera** [comment]
That's ok, I'm in no hurry. Thanks for your efforts!

The improvements sound good to me. If you could send a PR my way I'll look it over in the next few days.

**Comment by libre-man** [comment]
Should we make the BFS available with some sort of flag, as I don't know if the DFS is better in every case and the code is already there just a bit more to maintain I guess.

**Comment by Shinmera** [comment]
An optional argument to `select` to choose which of the two to use, while defaulting to DFS would be best, I suppose.

**Comment by Shinmera** [comment]
With the merge, this issue is now resolved.
