### ISSUE TITLE
Seeing the text of selected elements when working in the REPL - nice element printing

### ISSUE THREAD

**Issue by vindarel** [Shinmera/CLSS#8]
Hi,
when I use clss:select, it returns a vector of `plump-dom:element`s that are printed like this:

    (clss:select ".title" (plump:parse (dex:get "...")))
    ;; #(#<PLUMP-DOM:ELEMENT h1 {100759BED3}>)

as such we can not have a visual feedback of the stuff we just selected. It makes working in the REPL more difficult than it should.

To check my result I have to (look for a way and) do something like

    (map 'vector (lambda (it) (plump-dom:text  it)) *my-selected-elements*)

but doing this everytime isn't a solution.

The nice thing in Python's Beautifulsoup is that it prints the text of the node.

Could CLSS do this ? I imagine a global variable that we could set inside the REPL. How would you tackle this ? 

Regards

**Comment by Shinmera** [comment]
The DOM implementation is not CLSS' concern, since that belongs to Plump. Doing anything about it from within CLSS would be interfering with another library, and thus a no-go.

I don't want to make elements print their contents from Plump either, as that would mean the REPL would be spammed when all you want is to look at the DOM structure.

Either way, CLSS was never really intended to be used directly, and should rather be seen as an intermediary layer. You should use something like [lQuery](http://shinmera.github.io/lquery/) instead, which allows you to print contents easily as well.

**Comment by vindarel** [comment]
> CLSS was never really intended to be used directly

ok 

I have the same request for lquery :) Doing

    (lquery:$ *SOUP* ".title")

prints

    #(#<PLUMP-DOM:ELEMENT h1 {1003CE1543}>)

where it would be much easier to me if it printed

    #("Literate DevOps")


I understand it may not be useful to you. But could we have an option ?

**Comment by Shinmera** [comment]
You can append `(text)` in an lQuery form to see the textual contents, or use `(lquery:$ * (text))` after you've fetched something. You could also add a `print-object` method specialized on `plump-dom:element` yourself to get the behaviour you wanted.

I see this as a trivial enough thing for an end-user to do themselves, and a too-specific case to include in any of the involved libraries as a general feature.

**Comment by vindarel** [comment]
Oh, `(text)` is easy indeed, thank you. That's fantastic even. Great lib.

I'm also interested in print-object. I didn't try yet and I see the CLHS spec, however if you could give me more pointers or examples that would be very helpful.

**Comment by Shinmera** [comment]
Something like this.

```
(defmethod print-object ((element plump-dom:element) stream)
  (print-unreadable-object (element stream)
    (format stream "N ~s" (plump-dom:text element))))
```

I don't recommend doing this, as it will override the method that is already in place, and might quickly cause things to become hard to distinguish.

**Comment by vindarel** [comment]
thanks !

(I plan to finish a tutorial on this subject for the CL cookbook in a couple of days, I'll let you know).

**Comment by Shinmera** [comment]
Sure. If you have any other questions, let me know.
